apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-next-express-sa
  namespace: aws-next-express
  labels:
    app: aws-next-express
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/eks-pod-execution-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aws-next-express
  name: aws-next-express-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-next-express-rolebinding
  namespace: aws-next-express
subjects:
- kind: ServiceAccount
  name: aws-next-express-sa
  namespace: aws-next-express
roleRef:
  kind: Role
  name: aws-next-express-role
  apiGroup: rbac.authorization.k8s.io 