# Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: aws-next-express
  labels:
    app: aws-next-express
type: Opaque
stringData:
  # Database connection (update with real values)
  database-url: "mysql://appuser:changeme@mysql-service:3306/nextapp_db"
  
  # NextAuth configuration
  nextauth-secret: "your-nextauth-secret-key-here" # Generate with: openssl rand -base64 32
  nextauth-url: "https://your-domain.com"
  
  # AWS credentials (if not using IRSA)
  aws-access-key-id: "your-aws-access-key"
  aws-secret-access-key: "your-aws-secret-key"
  s3-bucket-name: "your-s3-bucket-name"
  
  # External API keys
  stripe-secret-key: "sk_test_your_stripe_secret_key"
  sendgrid-api-key: "SG.your_sendgrid_api_key"
---
# MySQL Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: aws-next-express
  labels:
    app: mysql
type: Opaque
stringData:
  root-password: "your-mysql-root-password"
  user-password: "your-mysql-user-password"
---
# Redis Cache Secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: aws-next-express
  labels:
    app: redis
type: Opaque
stringData:
  password: "your-redis-password"
---
# TLS Certificate Secret (for HTTPS)
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: aws-next-express
  labels:
    app: aws-next-express
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  # Replace with your actual certificate
  tls.crt: LS0tLS1CRUdJTi... # Your certificate here
  tls.key: LS0tLS1CRUdJTi... # Your private key here
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  AWS_REGION: "us-east-1"
  DYNAMODB_USERS_TABLE: "users" 