apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  access-key-id: "${AWS_ACCESS_KEY_ID_BASE64}"
  secret-access-key: "${AWS_SECRET_ACCESS_KEY_BASE64}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  AWS_REGION: "us-east-1"
  DYNAMODB_USERS_TABLE: "users" 